export { default as Background } from "./Background";
export { default as Navbar } from "./Navbar";
export { default as Welcome } from "./Welcome";
export { default as Features } from "./Features";
export { default as Testimonials } from "./Testimonials";
export { default as FrequentlyAskedQuestions } from "./FrequentlyAskedQuestions";
export { default as Advantages } from "./Advantages";
export { default as Highlights } from "./Highlights";
export { default as Footer } from "./Footer";
